version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    ECR_REGISTRY: "195275633219.dkr.ecr.us-east-1.amazonaws.com"
    REPO_NAME: "eks-repo"
    IMAGE_TAG: "wordpress-final"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REGISTRY/$REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $ECR_REGISTRY/$REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG
      - docker push $ECR_REGISTRY/$REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Updating Kubernetes manifest...
      - sed -i "s|{{IMAGE}}|$ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG|g" Deployment.yaml
      - echo Build completed
artifacts:
  files:
    - Deployment.yaml
    - service.yaml
    - ingress.yaml