version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    EKS_CLUSTER_NAME: "my-eks-cluster"
    K8S_NAMESPACE: "eks-project"
    DEPLOYMENT_NAME: "wordpress"

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

  build:
    commands:
      - echo Applying updated Kubernetes manifests...
      - kubectl apply -f Deployment.yaml -n $K8S_NAMESPACE
      - kubectl apply -f service.yaml -n $K8S_NAMESPACE
      - kubectl apply -f ingress.yaml -n $K8S_NAMESPACE
      - kubectl apply -f hpa.yaml -n $K8S_NAMESPACE
      - echo Restarting the deployment to apply the new image...
      - kubectl rollout restart deployment $DEPLOYMENT_NAME -n $K8S_NAMESPACE
      - echo Verifying deployment rollout...
      - kubectl rollout status deployment $DEPLOYMENT_NAME -n $K8S_NAMESPACE
