version: 0.2
phases:
  install:
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl || { echo "Failed to download kubectl"; exit 1; }
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/
  build:
    commands:
      - echo Deploying to EKS cluster...
      - aws --version || { echo "AWS CLI not found"; exit 1; }
      - aws sts get-caller-identity || { echo "AWS CLI credentials not working"; exit 1; }
      - aws eks list-clusters --region us-east-1 || { echo "Failed to list EKS clusters"; exit 1; }
      - echo "Checking cluster existence..."
      - aws eks describe-cluster --name my-eks-cluster --region us-east-1 || { echo "Failed to describe cluster my-eks-cluster"; exit 1; }
      - aws eks update-kubeconfig --name my-eks-cluster --region us-east-1 --debug || { echo "Failed to update kubeconfig"; exit 1; }
      - kubectl version || { echo "kubectl not working"; exit 1; }
      - kubectl apply -f Deployment.yaml || { echo "Failed to apply Deployment.yaml"; exit 1; }
      - kubectl apply -f service.yaml || { echo "Failed to apply service.yaml"; exit 1; }
      - kubectl apply -f ingress.yaml || { echo "Failed to apply ingress.yaml"; exit 1; }