apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: eks-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      serviceAccountName: wordpress-sa
      volumes:
        - name: secret-vol
          emptyDir: {}

      initContainers:
        - name: fetch-secrets
          image: amazonlinux:2
          command: ["/bin/sh", "-c"]
          args:
            - |
              yum install -y aws-cli jq;
              SECRET=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id rds-db-secret-Btidr5 --query SecretString --output text);
              echo "$SECRET" | jq -r '.host' > /secrets/WORDPRESS_DB_HOST;
              echo "$SECRET" | jq -r '.username' > /secrets/WORDPRESS_DB_USER;
              echo "$SECRET" | jq -r '.password' > /secrets/WORDPRESS_DB_PASSWORD;
              echo "$SECRET" | jq -r '.dbname' > /secrets/WORDPRESS_DB_NAME;
          volumeMounts:
            - name: secret-vol
              mountPath: /secrets

      containers:
        - name: wordpress
          image: 195275633219.dkr.ecr.us-east-1.amazonaws.com/eks-repo:wordpress-final
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              export WORDPRESS_DB_HOST=$(cat /secrets/WORDPRESS_DB_HOST)
              export WORDPRESS_DB_USER=$(cat /secrets/WORDPRESS_DB_USER)
              export WORDPRESS_DB_PASSWORD=$(cat /secrets/WORDPRESS_DB_PASSWORD)
              export WORDPRESS_DB_NAME=$(cat /secrets/WORDPRESS_DB_NAME)
              exec docker-entrypoint.sh apache2-foreground
          volumeMounts:
            - name: secret-vol
              mountPath: /secrets
