apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: eks-project 
  name: pipeline-deployer
rules:
- apiGroups: ["", "apps", "networking.k8s.io", "autoscaling"]
  resources: ["deployments", "services", "ingresses", "horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-deployer-binding
  namespace: default
subjects:
- kind: User
  name: pipeline-role
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pipeline-deployer
  apiGroup: rbac.authorization.k8s.io